- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Allow anything from management IPs
  ufw:
    rule: allow
    src: "{{ item }}"
  loop: "{{ config.root_acl }}"

- name: Allow looking glass BGP
  ufw:
    rule: allow
    src: "{{ config.lg }}"
    port: 179

- name: Allow control plane ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 80
    - 443
  when: "'controlplane' in group_names"

- name: Allow edge ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 53
  when: "'edge' in group_names"

- name: Set default deny
  ufw:
    state: enabled
    policy: deny
    logging: "off"
