- name: Install knot and pip3
  apt:
    update-cache: true
    pkg:
      - knot
      - python3-pip

- name: Copy knot.conf
  template:
    src: knot.conf
    dest: /etc/knot/knot.conf
  register: knot_conf

- name: Make /etc/knot/as112/ directory
  file:
    path: /etc/knot/as112/
    state: directory

- name: Copy AS112 zone files
  template:
    src: "{{ item }}"
    dest: /etc/knot/as112/{{ item | basename }}
  with_fileglob:
    - ../templates/as112/*
  register: as112_zones

- name: Create empty zones file if it doesn't exist
  copy:
    content: ""
    dest: /opt/packetframe/dns/knot.zones.conf
    force: no

- name: Reload knot
  systemd:
    name: knot
    state: restarted
  when: knot_conf.changed or as112_zones.changed

- name: Install prometheus client
  pip:
    executable: /usr/bin/pip3
    name: prometheus_client

- name: Copy knot_exporter.py
  template:
    src: knot_exporter.py
    dest: /usr/local/bin/knot_exporter
    mode: +x
  register: knot_exporter

- name: Copy knot-exporter.service
  template:
    src: knot-exporter.service
    dest: /lib/systemd/system/knot-exporter.service
  register: knot_exporter_service

- name: Start knot-exporter
  systemd:
    daemon-reload: true
    name: knot-exporter
    state: started
    enabled: true

- name: Restart knot-exporter
  systemd:
    name: knot-exporter
    state: restarted
  when: knot_exporter.changed or knot_exporter_service.changed
