- name: Control plane install
  hosts: controlplane
  vars_files:
    - config/controlplane-versions.yml
  roles:
    - role: "./roles/controlplane/bashrc"
    - role: "./roles/common/firewall"
    - role: "./roles/common/install_docker"
    - role: "./roles/controlplane/wireguard"
    - role: "./roles/controlplane/docker_compose"
    - role: "./roles/controlplane/deploy_web"
