- name: Control plane install
  hosts: controlplane
  vars_files:
    - config/controlplane-versions.yml
  roles:
    - role: "./roles/common/firewall"
    - role: "./roles/common/install_docker"
    - role: "./roles/controlplane/docker_compose"
