- name: Control plane install
  hosts: controlplane
  vars_files:
    - config/controlplane-versions.yml
  roles:
    - role: "./roles/controlplane/bashrc"
    - role: "./roles/common/firewall"
    - role: "./roles/common/install_docker"

- name: Control plane update
  hosts: controlplane
  vars_files:
    - config/controlplane-versions.yml
  roles:
    - role: "./roles/controlplane/wireguard"
    - role: "./roles/controlplane/docker_compose"
    - role: "./roles/controlplane/deploy_web"

- name: LG update
  hosts: lg
  roles:
    - role: "./roles/controlplane/lg"
