- name: Edge install
  hosts: edge
  vars_files:
    - config/controlplane-versions.yml
    - config/edge-versions.yml
  roles:
    - role: "./roles/common/firewall"
    - role: "./roles/common/auth"
    - role: "./roles/edge/system"
    - role: "./roles/edge/knot"
    - role: "./roles/edge/verfploeter"
    - role: "./roles/edge/nodeexporter"
    - role: "./roles/edge/birdexporter"
    - role: "./roles/edge/edgemonitor"
    - role: "./roles/edge/bgp"

- name: Bootstrap nodes
  hosts: controlplane
  roles:
    - role: "./roles/controlplane/bootstrap_nodes"
