- name: Edge install
  hosts: edge
  roles:
    - role: "./roles/common/firewall"
    - role: "./roles/common/auth"
    - role: "./roles/edge/system"
    - role: "./roles/edge/coredns"
    - role: "./roles/edge/bgp"
