- name: Update controlplane nodes
  hosts: controlplane
  vars_files:
    - config/controlplane-versions.yml
  roles:
    - role: "./roles/controlplane/docker_compose"

- name: Edge install
  hosts: edge
  vars_files:
    - config/controlplane-versions.yml
    - config/edge-versions.yml
  roles:
    - role: "./roles/common/firewall"
    - role: "./roles/edge/wireguard"
    - role: "./roles/common/auth"
    - role: "./roles/edge/system"
    - role: "./roles/edge/sysctl"
    - role: "./roles/edge/knot"
    - role: "./roles/edge/verfploeter"
    - role: "./roles/edge/nodeexporter"
    - role: "./roles/edge/birdexporter"
    - role: "./roles/edge/edgemonitor"
    - role: "./roles/edge/bgp"
