# TODO: Remove
- name: stop verfploeter
  systemd:
    name: verfploeter
    state: stopped
- name: Remove
  group:
    name: verfploeter
    state: absent
- name: Remove
  user:
    name: verfploeter
    state: absent
- name: Create pfservice group
  group:
    name: pfservice
    state: present
- name: Create pfservice user
  user:
    name: pfservice
    groups: pfservice
    shell: /sbin/nologin

- name: Download node-exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ edge_versions.archive['node-exporter'] }}/node_exporter-{{ edge_versions.archive['node-exporter'] }}.linux-amd64.tar.gz"
    remote_src: yes
    dest: /tmp/
  register: nodeexporter_download

- name: Copy node-exporter
  shell: "mv /tmp/node_exporter-{{ edge_versions.archive['node-exporter'] }}.linux-amd64/node_exporter /usr/local/bin/node_exporter && rm -rf /tmp/node_exporter-{{ edge_versions.archive['node-exporter'] }}.linux-amd64/"
  when: nodeexporter_download.changed

- name: Copy node-exporter.service
  template:
    src: node-exporter.service
    dest: /lib/systemd/system/node-exporter.service
  register: nodeexporter_config

- name: Enable and start node-exporter
  systemd:
    daemon_reload: true
    name: node-exporter
    state: started
    enabled: true

- name: Restart node-exporter
  systemd:
    name: node-exporter
    state: restarted
  when: nodeexporter_config.changed
