version: "3.3"
services:
  caddy:
    image: "caddy:{{ controlplane_versions.docker.caddy }}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/packetframe/docker/caddy/data/:/data
      - /opt/packetframe/docker/caddy/public/:/etc/caddy/public/
      - /opt/packetframe/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/packetframe/docker/caddy/log.txt:/var/log/caddy.log

  api:
    image: "ghcr.io/packetframe/api:{{ controlplane_versions.docker.api }}"
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - api_db
    environment:
      - DB_HOST=api_db
      - METRICS_LISTEN=:8081
      - RPC_SERVER=http://orchestrator:8080

  orchestrator:
    image: "ghcr.io/packetframe/orchestrator:{{ controlplane_versions.docker.api }}"
    volumes:
      - /opt/packetframe/docker/orchestrator_cache/:/data
      - /root/.ssh/packetframe:/ssh-key
      - /opt/packetframe/docker/nodes.yml:/nodes.yml
    depends_on:
      - api_db
    environment:
      - DB_HOST=api_db
      - CACHE_DIR=/data
      - METRICS_LISTEN=:8081
      - RPC_LISTEN=:8080
      - SSH_KEY_FILE=/ssh-key
      - SSH_PORT={{ config.edge.ssh.port }}
      - NODE_FILE=/nodes.yml
      - NS1_HOSTNAME=ns1v4
      - NS2_HOSTNAME=ns2v4

  api_db:
    image: "postgres:{{ controlplane_versions.docker.postgres }}"
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - /opt/packetframe/docker/api_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api

  prometheus:
    image: "prom/prometheus:v{{ controlplane_versions.docker.prometheus }}"
    user: root
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - /opt/packetframe/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/packetframe/docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
