global:
  scrape_interval: 30s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "controlplane"
    metric_relabel_configs:
      - source_labels: [ "__name__" ]
        regex: "^(go).*$"
        action: drop
    static_configs:
      - targets:
        - api:8081
        - vertex:8081

  - job_name: "node"
    static_configs:
{% for host in groups["edge"] %}
      - targets: ["{{ hostvars[host]['ansible_host'] }}:9100"]
        labels:
          node: {{ host }}
{% endfor %}

  - job_name: "knot"
    static_configs:
{% for host in groups["edge"] %}
      - targets: ["{{ hostvars[host]['ansible_host'] }}:9433"]
        labels:
          node: {{ host }}
{% endfor %}

  - job_name: "bird"
    static_configs:
{% for host in groups["edge"] %}
      - targets: ["{{ hostvars[host]['ansible_host'] }}:9324"]
        labels:
          node: {{ host }}
{% endfor %}

  - job_name: "verfploeter"
    metric_relabel_configs:
      - source_labels: [ "__name__" ]
        regex: "^(go).*$"
        action: drop
    static_configs:
{% for host in groups["edge"] %}
      - targets: ["{{ hostvars[host]['ansible_host'] }}:9918"]
        labels:
          node: {{ host }}
{% endfor %}
