controlplane_versions:
  debian: bullseye
  docker:
    api: 0.0.70
    postgres: 14.1-bullseye
    caddy: 2.4.6-alpine
    prometheus: 2.31.1
    grafana: 8.3.4
    bifocal: 0.0.3
    vertex: 0.0.7
  archives:
    web: 0.0.75
