edge_versions:
  debian: bullseye
  apt:
    pathvector: 5.12.0
    bird2: 2.0.8-2~bpo11+1
  archive:
    node-exporter: 1.3.1
    go-verfploeter: 0.0.2
    bird-exporter: 1.4.1 # https://github.com/czerwonk/bird_exporter/releases/latest
    xdpfw: 0.0.3 # https://github.com/packetframe/XDP-Firewall/releases/latest
    pfcaddy: 0.0.10
