edge_versions:
  debian: bullseye
  apt:
    pathvector: 5.8.0
    bird2: 2.0.8-2~bpo11+1
    mtr: 0.94-1+deb11u1
    rsync: 3.2.3-4+deb11u1
    knot-dnsutils: 3.1.5-cznic.1~bullseye
    go-verfploeter: 0.0.2
    knot: 3.1.5-cznic.1~bullseye
