- name: Copy betteruptime-incident.py
  template:
    src: betteruptime-incident.py
    dest: /usr/local/bin/betteruptime-incident
    mode: +x

- name: Copy edgemonitor.sh
  template:
    src: edgemonitor.sh
    dest: /usr/local/bin/edge-monitor
    mode: +x
#
#- name: Add crontab entry
#  cron:
#    name: edgemonitor
#    user: root
#    job: /usr/local/bin/edge-monitor
#    minute: "*"
