asn: 34553
router-id: 66.248.234.1
prefixes:
  - 66.248.234.0/24
  - 2602:809:3004::/48
default-route: false
accept-default: true
portal-host: "{{ config.edge.portal.host }}"
portal-key: "{{ config.edge.portal.key }}"
hostname: "edge1.{{ inventory_hostname }}"
templates:
  upstream:
    allow-local-as: true
    announce-communities: [ "34553,15" ]
    remove-all-communities: 34553
    local-pref: 80
    import-communities: [ "34553,12" ]
    export-communities: [ "34553,33,{{ node_id }}" ]
    filter-prefix-length: false

  routeserver:
    filter-transit-asns: true
    auto-import-limits: true
    enforce-peer-nexthop: false
    enforce-first-as: false
    announce-communities: [ "34553,15" ]
    remove-all-communities: 34553
    local-pref: 90
    export-communities: [ "34553,33,{{ node_id }}" ]
    import-communities: [ "34553,13" ]

  peer:
    filter-irr: true
    filter-transit-asns: true
    auto-import-limits: true
    auto-as-set: true
    announce-communities: [ "34553,15" ]
    remove-all-communities: 34553
    local-pref: 100
    export-communities: [ "34553,33,{{ node_id }}" ]
    import-communities: [ "34553,14" ]

  downstream:
    filter-irr: true
    allow-blackhole-community: true
    filter-transit-asns: true
    auto-import-limits: true
    auto-as-set: true
    announce-communities: [ "34553,15" ]
    announce-default: true
    remove-all-communities: 34553
    local-pref: 200
    export-communities: [ "34553,33,{{ node_id }}" ]
    import-communities: [ "34553,15" ]

{{ bgp | to_nice_yaml }}
