- name: Copy Pathvector config
  template:
    src: pathvector.yml
    dest: /etc/pathvector.yml
  register: pathvector_config

- name: Generate Pathvector output
  shell: pathvector generate
  when: pathvector_config.changed

- name: Add crontab entry
  cron:
    name: Pathvector generate
    user: root
    job: /usr/local/bin/pathvector generate
    minute: "0"
    hour: "*/12"

# TODO: Remove this
- name: Add portal crontab entry
  cron:
    name: Pathvector portal update
    user: root
    job: /usr/local/bin/pathvector portal-update
    minute: "*/15"
